name: Maven Package

on:
  release:
    types: [created]  # Run this workflow when a new release is created

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Permissions needed to write to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github  # This must match the id in your pom.xml distributionManagement section
          settings-path: ${{ github.workspace }}  # Path to where the settings.xml will be created

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build and Package with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token automatically provided by GitHub Actions

      - name: Archive build artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/*.jar
