name: Maven Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Permissions needed to write to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github  # This must match the id in your pom.xml distributionManagement section
          settings-path: ${{ github.workspace }}  # Path to where the settings.xml will be created

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Set Version with SemVer (Patch Increment)
        id: semver
        run: |
          # Get the current version from pom.xml
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current Version: $CURRENT_VERSION"

          # Strip the `-SNAPSHOT` suffix and increment the patch version
          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-SNAPSHOT//')
          NEW_VERSION=$(echo $BASE_VERSION | awk -F. -v OFS=. '{$NF = $NF + 1; print}')
          
          # Append `-SNAPSHOT` to the new version
          FINAL_VERSION="$NEW_VERSION-SNAPSHOT"
          echo "New Version: $FINAL_VERSION"

          # Update the version in pom.xml
          mvn versions:set -DnewVersion=$FINAL_VERSION
          mvn versions:commit   


      - name: Build and Package with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token automatically provided by GitHub Actions

      - name: Archive build artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/*.jar